APP_NAME: "go-boilerplate"
APP_PORT: 1233
READ_TIMEOUT:
WRITE_TIMEOUT:
CTX_TIMEOUT:

JWT_SECRET:
JWT_EXPIRED_TOKEN_DURATION:
JWT_ISSUER:

DB_HOST:
DB_PORT:
DB_USER: ""
DB_PASSWORD: ""
DB_NAME: ""
DB_SSL_MODE: ""
